#!/bin/bash
echo "\"(Ôo)'"
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
1-confused_smiley[+] [unix] (00:59 01/01/1970)                           2,7 All
-- INSERT --
"
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
1-confused_smiley[+] [unix] (00:59 01/01/1970)                           2,7 All
-- INSERT --
"
